import { ThemePreset } from '../types';

export interface ThemeConfig {
  id: ThemePreset;
  name: string;
  category: 'light' | 'dark' | 'vibrant';
  bgClass: string;
  containerBg: string;
  cardClass: string;
  cardHover: string;
  textPrimary: string;
  textSecondary: string;
  avatarBorder: string;
  badgeClass: string;
  accentColor: string;
  previewColor: string;
}

export const THEME_CONFIGS: Record<ThemePreset, ThemeConfig> = {
  vibrant: {
    id: 'vibrant',
    name: 'Vibrant Pop (Default)',
    category: 'vibrant',
    bgClass: 'bg-[#FFFDF5]',
    containerBg: 'bg-white border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]',
    cardClass: 'bg-white border-2 border-black text-[#1A1A1A] font-bold shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]',
    cardHover: 'hover:bg-[#FFD600] hover:text-black hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] active:translate-y-1 active:shadow-none',
    textPrimary: 'text-[#1A1A1A] font-black',
    textSecondary: 'text-slate-600 font-medium',
    avatarBorder: 'border-2 border-black bg-[#FF80B5] ring-4 ring-[#FFD600]/30',
    badgeClass: 'bg-[#FFD600] text-black font-black border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]',
    accentColor: '#FFD600',
    previewColor: '#FFFDF5',
  },
  minimal: {
    id: 'minimal',
    name: 'Clean Chalk',
    category: 'light',
    bgClass: 'bg-[#F8FAFC]',
    containerBg: 'bg-white border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]',
    cardClass: 'bg-white border-2 border-black text-neutral-900 font-bold shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]',
    cardHover: 'hover:bg-neutral-100 hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-[1px_1px_0px_0px_rgba(0,0,0,1)]',
    textPrimary: 'text-neutral-950 font-black',
    textSecondary: 'text-neutral-600',
    avatarBorder: 'border-2 border-black ring-4 ring-neutral-200',
    badgeClass: 'bg-white text-black font-bold border-2 border-black',
    accentColor: '#171717',
    previewColor: '#ffffff',
  },
  midnight: {
    id: 'midnight',
    name: 'Obsidian Night',
    category: 'dark',
    bgClass: 'bg-[#0F172A]',
    containerBg: 'bg-[#1E293B] border-2 border-white/80 shadow-[4px_4px_0px_0px_#6366F1]',
    cardClass: 'bg-[#1E293B] border-2 border-white text-white font-bold shadow-[3px_3px_0px_0px_#6366F1]',
    cardHover: 'hover:bg-[#6366F1] hover:text-white hover:border-white hover:translate-x-0.5 hover:translate-y-0.5',
    textPrimary: 'text-white font-black',
    textSecondary: 'text-slate-300',
    avatarBorder: 'border-2 border-white ring-4 ring-[#6366F1]/50',
    badgeClass: 'bg-[#6366F1] text-white border-2 border-white',
    accentColor: '#6366F1',
    previewColor: '#0F172A',
  },
  sunset: {
    id: 'sunset',
    name: 'Electric Sunset',
    category: 'vibrant',
    bgClass: 'bg-gradient-to-b from-[#FFF1F2] via-[#FFF7ED] to-[#FEF3C7]',
    containerBg: 'bg-white border-2 border-black shadow-[4px_4px_0px_0px_#FF80B5]',
    cardClass: 'bg-[#FF80B5] border-2 border-black text-black font-bold shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]',
    cardHover: 'hover:bg-[#FFD600] hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-[1px_1px_0px_0px_rgba(0,0,0,1)]',
    textPrimary: 'text-neutral-950 font-black',
    textSecondary: 'text-neutral-700',
    avatarBorder: 'border-2 border-black bg-[#FF80B5] ring-4 ring-rose-300',
    badgeClass: 'bg-[#FFD600] text-black border-2 border-black font-bold',
    accentColor: '#FF80B5',
    previewColor: '#FFF1F2',
  },
  emerald: {
    id: 'emerald',
    name: 'Mint Botanic',
    category: 'light',
    bgClass: 'bg-[#ECFDF5]',
    containerBg: 'bg-white border-2 border-black shadow-[4px_4px_0px_0px_#10B981]',
    cardClass: 'bg-[#10B981] border-2 border-black text-white font-bold shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]',
    cardHover: 'hover:bg-[#059669] hover:translate-x-0.5 hover:translate-y-0.5',
    textPrimary: 'text-emerald-950 font-black',
    textSecondary: 'text-emerald-800',
    avatarBorder: 'border-2 border-black bg-[#10B981] ring-4 ring-emerald-300',
    badgeClass: 'bg-[#10B981] text-white border-2 border-black font-bold',
    accentColor: '#10B981',
    previewColor: '#ECFDF5',
  },
  ocean: {
    id: 'ocean',
    name: 'Electric Cyan',
    category: 'dark',
    bgClass: 'bg-[#0C4A6E]',
    containerBg: 'bg-[#0284C7] border-2 border-white shadow-[4px_4px_0px_0px_#38BDF8]',
    cardClass: 'bg-white border-2 border-black text-neutral-900 font-bold shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]',
    cardHover: 'hover:bg-[#38BDF8] hover:translate-x-0.5 hover:translate-y-0.5',
    textPrimary: 'text-white font-black',
    textSecondary: 'text-sky-100',
    avatarBorder: 'border-2 border-white ring-4 ring-sky-300',
    badgeClass: 'bg-white text-black border-2 border-black font-bold',
    accentColor: '#38BDF8',
    previewColor: '#0C4A6E',
  },
  lavender: {
    id: 'lavender',
    name: 'Pastel Lilac',
    category: 'light',
    bgClass: 'bg-[#FAF5FF]',
    containerBg: 'bg-white border-2 border-black shadow-[4px_4px_0px_0px_#C084FC]',
    cardClass: 'bg-[#E9D5FF] border-2 border-black text-purple-950 font-bold shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]',
    cardHover: 'hover:bg-[#C084FC] hover:text-white hover:translate-x-0.5 hover:translate-y-0.5',
    textPrimary: 'text-purple-950 font-black',
    textSecondary: 'text-purple-700',
    avatarBorder: 'border-2 border-black bg-[#E9D5FF] ring-4 ring-purple-300',
    badgeClass: 'bg-[#C084FC] text-white border-2 border-black font-bold',
    accentColor: '#C084FC',
    previewColor: '#FAF5FF',
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber Neo',
    category: 'dark',
    bgClass: 'bg-[#18181B]',
    containerBg: 'bg-black border-2 border-[#FFD600] shadow-[4px_4px_0px_0px_#FFD600]',
    cardClass: 'bg-[#FFD600] border-2 border-black text-black font-mono font-black shadow-[3px_3px_0px_0px_#FFFFFF]',
    cardHover: 'hover:bg-white hover:text-black hover:translate-x-0.5 hover:translate-y-0.5',
    textPrimary: 'text-[#FFD600] font-mono font-black',
    textSecondary: 'text-zinc-300 font-mono',
    avatarBorder: 'border-2 border-[#FFD600] ring-4 ring-[#FFD600]/30',
    badgeClass: 'bg-[#FFD600] text-black border-2 border-black font-bold font-mono',
    accentColor: '#FFD600',
    previewColor: '#18181B',
  },
  rose: {
    id: 'rose',
    name: 'Bubblegum Pop',
    category: 'light',
    bgClass: 'bg-[#FFF1F2]',
    containerBg: 'bg-white border-2 border-black shadow-[4px_4px_0px_0px_#FB7185]',
    cardClass: 'bg-[#FFE4E6] border-2 border-black text-rose-950 font-bold shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]',
    cardHover: 'hover:bg-[#FB7185] hover:text-white hover:translate-x-0.5 hover:translate-y-0.5',
    textPrimary: 'text-rose-950 font-black',
    textSecondary: 'text-rose-700',
    avatarBorder: 'border-2 border-black bg-[#FB7185] ring-4 ring-rose-300',
    badgeClass: 'bg-[#FB7185] text-white border-2 border-black font-bold',
    accentColor: '#FB7185',
    previewColor: '#FFF1F2',
  },
};
